//! `coral project lock` — regenerate `coral.lock` from the manifest without
//! pulling. Idempotent dry-run of `coral project sync`.
//!
//! Reads the existing lockfile (if any) and the manifest. Emits a
//! refreshed lockfile entry per repo with **the SHA already present
//! (or zeros if absent)**. Real ref-resolution + git fetch lands in
//! v0.16.x with `coral project sync`.

use anyhow::{Context, Result};
use chrono::Utc;
use clap::Args;
use coral_core::project::{Lockfile, RepoLockEntry};
use std::path::Path;
use std::process::ExitCode;

use crate::commands::common::resolve_project;

#[derive(Args, Debug)]
pub struct LockArgs {
    /// Dry-run: print the lockfile contents to stdout instead of writing.
    #[arg(long)]
    pub dry_run: bool,
}

pub fn run(args: LockArgs, wiki_root: Option<&Path>) -> Result<ExitCode> {
    let project = resolve_project(wiki_root)?;
    if project.is_legacy() {
        anyhow::bail!(
            "`coral project lock` requires a coral.toml; this is a legacy single-repo project"
        );
    }

    let lock_path = project.lockfile_path();
    let mut lock = Lockfile::load_or_default(&lock_path)
        .with_context(|| format!("loading {}", lock_path.display()))?;

    let now = Utc::now();
    for repo in &project.repos {
        if !repo.enabled {
            continue;
        }
        let in_place = repo
            .path
            .as_ref()
            .map(|p| p == Path::new("."))
            .unwrap_or(false);
        if in_place {
            continue;
        }
        let url = match project.resolved_url(repo) {
            Some(u) => u,
            None => continue,
        };
        let r#ref = repo
            .r#ref
            .clone()
            .unwrap_or_else(|| project.defaults.r#ref.clone());

        let sha = lock
            .repos
            .get(&repo.name)
            .map(|e| e.sha.clone())
            .unwrap_or_else(|| "0000000000000000000000000000000000000000".to_string());

        lock.upsert(
            &repo.name,
            RepoLockEntry {
                url,
                r#ref,
                sha,
                synced_at: now,
            },
        );
    }

    // Drop entries that no longer correspond to a repo.
    let manifest_names: std::collections::BTreeSet<&str> =
        project.repos.iter().map(|r| r.name.as_str()).collect();
    let stale: Vec<String> = lock
        .repos
        .keys()
        .filter(|k| !manifest_names.contains(k.as_str()))
        .cloned()
        .collect();
    for name in stale {
        lock.repos.remove(&name);
    }

    if args.dry_run {
        print!("{lock}");
        return Ok(ExitCode::SUCCESS);
    }
    lock.write_atomic(&lock_path)
        .with_context(|| format!("writing {}", lock_path.display()))?;
    println!("✔ updated {}", lock_path.display());
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn lock_writes_lockfile_for_declared_repos() {
        let _guard = crate::commands::CWD_LOCK
            .lock()
            .unwrap_or_else(|p| p.into_inner());
        let dir = TempDir::new().unwrap();
        std::fs::write(
            dir.path().join("coral.toml"),
            r#"apiVersion = "coral.dev/v1"
[project]
name = "demo"

[[repos]]
name = "api"
url = "git@example.com:acme/api.git"
"#,
        )
        .unwrap();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        let result = run(LockArgs { dry_run: false }, None);
        std::env::set_current_dir(original).unwrap();
        assert!(result.is_ok());

        let raw = std::fs::read_to_string(dir.path().join("coral.lock")).unwrap();
        let lock = Lockfile::parse(&raw).unwrap();
        assert_eq!(lock.repos.len(), 1);
        assert!(lock.repos.contains_key("api"));
    }

    #[test]
    fn lock_drops_stale_entries() {
        let _guard = crate::commands::CWD_LOCK
            .lock()
            .unwrap_or_else(|p| p.into_inner());
        let dir = TempDir::new().unwrap();
        std::fs::write(
            dir.path().join("coral.toml"),
            r#"apiVersion = "coral.dev/v1"
[project]
name = "demo"

[[repos]]
name = "api"
url = "git@example.com:acme/api.git"
"#,
        )
        .unwrap();
        // Pre-seed lock with a stale 'gone' entry.
        std::fs::write(
            dir.path().join("coral.lock"),
            r#"# Generated by `coral project sync`
apiVersion = "coral.dev/v1"
resolved_at = "2026-05-01T00:00:00Z"

[repos.gone]
url = "git@example.com:acme/gone.git"
ref = "main"
sha = "deadbeef"
synced_at = "2026-05-01T00:00:00Z"
"#,
        )
        .unwrap();

        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        let result = run(LockArgs { dry_run: false }, None);
        std::env::set_current_dir(original).unwrap();
        assert!(result.is_ok());
        let raw = std::fs::read_to_string(dir.path().join("coral.lock")).unwrap();
        let lock = Lockfile::parse(&raw).unwrap();
        assert!(!lock.repos.contains_key("gone"));
        assert!(lock.repos.contains_key("api"));
    }

    #[test]
    fn lock_rejects_legacy_project() {
        let _guard = crate::commands::CWD_LOCK
            .lock()
            .unwrap_or_else(|p| p.into_inner());
        let dir = TempDir::new().unwrap();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(dir.path()).unwrap();
        let result = run(LockArgs { dry_run: false }, None);
        std::env::set_current_dir(original).unwrap();
        assert!(result.is_err());
    }
}
