//! Print the LintReport JSON schema to stdout.
//!
//! Mirrors `coral-stats`' `print_schema` example. Run from the repo root to
//! refresh the committed schema:
//!
//! ```sh
//! cargo run -p coral-lint --example dump_schema > docs/schemas/lint.schema.json
//! ```
//!
//! The output is the JSON schema (draft-07) generated by `schemars` from the
//! `LintReport` struct, and is the contract for `coral lint --format json`.
fn main() {
    println!("{}", coral_lint::LintReport::json_schema());
}
