//! `coral.lock` — resolved SHAs for the repos declared in `coral.toml`.
//!
//! The lockfile separates **intent** (the `ref = "main"` in the manifest)
//! from **resolved** (the SHA that was actually clone-ed). Same role as
//! `Cargo.lock` / `package-lock.json` / `MODULE.bazel.lock`. Written
//! atomically (tmp + rename) by `coral project sync`; read by every
//! command that needs reproducibility (e.g. `coral ingest --affected`).

use crate::error::{CoralError, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

#[derive(Debug, Clone, PartialEq)]
pub struct Lockfile {
    pub api_version: String,
    pub resolved_at: DateTime<Utc>,
    pub repos: BTreeMap<String, RepoLockEntry>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RepoLockEntry {
    pub url: String,
    pub r#ref: String,
    pub sha: String,
    pub synced_at: DateTime<Utc>,
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            api_version: super::manifest::CURRENT_API_VERSION.to_string(),
            resolved_at: Utc::now(),
            repos: BTreeMap::new(),
        }
    }

    pub fn upsert(&mut self, name: impl Into<String>, entry: RepoLockEntry) {
        self.repos.insert(name.into(), entry);
        self.resolved_at = Utc::now();
    }

    pub fn get(&self, name: &str) -> Option<&RepoLockEntry> {
        self.repos.get(name)
    }

    /// Parse a lockfile from on-disk TOML.
    pub fn parse(raw: &str) -> Result<Self> {
        let parsed: RawLockfile = toml::from_str(raw)
            .map_err(|e| CoralError::Walk(format!("failed to parse coral.lock: {}", e)))?;
        Ok(Self {
            api_version: parsed
                .api_version
                .unwrap_or_else(|| super::manifest::CURRENT_API_VERSION.to_string()),
            resolved_at: parsed.resolved_at.unwrap_or_else(Utc::now),
            repos: parsed.repos.unwrap_or_default(),
        })
    }

    /// Atomically write the lockfile to `path` (tmp + rename). Holds the
    /// project flock while writing so concurrent `coral project sync`
    /// invocations don't corrupt the file.
    pub fn write_atomic(&self, path: impl AsRef<Path>) -> Result<()> {
        let path = path.as_ref();
        let content = self.to_string();
        crate::atomic::with_exclusive_lock(path, || {
            crate::atomic::atomic_write_string(path, &content)
        })
    }

    /// Load from `path`. Returns a fresh empty lockfile when the file
    /// does not exist — same semantics as Cargo.lock auto-create.
    pub fn load_or_default(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        match std::fs::read_to_string(path) {
            Ok(s) => Self::parse(&s),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::new()),
            Err(source) => Err(CoralError::Io {
                path: path.to_path_buf(),
                source,
            }),
        }
    }
}

/// Render the lockfile as canonical TOML. Stable ordering: BTreeMap
/// for `repos`, ISO 8601 for timestamps. The `# Generated…` banner
/// comment is the convention all major lockfiles use. Implementing
/// `Display` (rather than an inherent `to_string`) avoids the
/// `clippy::inherent_to_string` lint and gives callers the standard
/// formatting traits — `format!("{lock}")` and `lock.to_string()` both
/// work and produce the same output.
impl fmt::Display for Lockfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "# Generated by `coral project sync` — do NOT edit by hand"
        )?;
        writeln!(f, "apiVersion = \"{}\"", self.api_version)?;
        writeln!(f, "resolved_at = \"{}\"", self.resolved_at.to_rfc3339())?;
        for (name, entry) in &self.repos {
            writeln!(f)?;
            writeln!(f, "[repos.{}]", name)?;
            writeln!(f, "url       = \"{}\"", entry.url)?;
            writeln!(f, "ref       = \"{}\"", entry.r#ref)?;
            writeln!(f, "sha       = \"{}\"", entry.sha)?;
            writeln!(f, "synced_at = \"{}\"", entry.synced_at.to_rfc3339())?;
        }
        Ok(())
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Deserialize)]
struct RawLockfile {
    #[serde(rename = "apiVersion")]
    api_version: Option<String>,
    resolved_at: Option<DateTime<Utc>>,
    repos: Option<BTreeMap<String, RepoLockEntry>>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use tempfile::TempDir;

    fn fixed_time() -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 5, 3, 14, 22, 11).unwrap()
    }

    #[test]
    fn new_lockfile_is_empty() {
        let lock = Lockfile::new();
        assert!(lock.repos.is_empty());
        assert_eq!(
            lock.api_version,
            super::super::manifest::CURRENT_API_VERSION
        );
    }

    #[test]
    fn roundtrip_preserves_entries() {
        let mut lock = Lockfile {
            api_version: "coral.dev/v1".to_string(),
            resolved_at: fixed_time(),
            repos: BTreeMap::new(),
        };
        lock.repos.insert(
            "api".to_string(),
            RepoLockEntry {
                url: "git@example.com:acme/api.git".to_string(),
                r#ref: "main".to_string(),
                sha: "abc123def4567890".to_string(),
                synced_at: fixed_time(),
            },
        );
        let rendered = lock.to_string();
        let parsed = Lockfile::parse(&rendered).unwrap();
        assert_eq!(parsed.repos.len(), 1);
        assert_eq!(parsed.repos.get("api").unwrap().sha, "abc123def4567890");
    }

    #[test]
    fn write_atomic_then_read_back() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("coral.lock");
        let mut lock = Lockfile::new();
        lock.upsert(
            "api",
            RepoLockEntry {
                url: "git@example.com:acme/api.git".to_string(),
                r#ref: "main".to_string(),
                sha: "deadbeefcafe".to_string(),
                synced_at: fixed_time(),
            },
        );
        lock.write_atomic(&path).unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        let parsed = Lockfile::parse(&raw).unwrap();
        assert_eq!(parsed.repos.get("api").unwrap().sha, "deadbeefcafe");
    }

    #[test]
    fn load_or_default_returns_empty_when_missing() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("does-not-exist.lock");
        let lock = Lockfile::load_or_default(&path).unwrap();
        assert!(lock.repos.is_empty());
    }

    /// v0.19.6 audit H3 regression: under concurrent load+upsert+write
    /// against the same `coral.lock`, BOTH writers' upserts must
    /// persist. Pre-fix the second writer's `load_or_default` ran after
    /// the first writer's `write_atomic` had committed — but ALSO read
    /// the OLD bytes if the two ran fully interleaved (read both old →
    /// modify both → write both, where the second write clobbered the
    /// first writer's entry). This reproduces the wrap-in-flock fix
    /// applied to `coral project sync`.
    ///
    /// Note: the closure body uses `atomic_write_string` directly
    /// rather than `Lockfile::write_atomic` because the latter would
    /// re-enter `with_exclusive_lock` from a fresh FD on the same
    /// inode, which can self-deadlock from a single process. The CLI
    /// `coral project sync` makes the same choice — see the comment
    /// over the `with_exclusive_lock` block in
    /// `crates/coral-cli/src/commands/project/sync.rs`.
    #[test]
    fn lockfile_concurrent_upsert_under_lock_preserves_both_entries() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("coral.lock");
        // Seed an empty lockfile so both writers see the same starting
        // state.
        Lockfile::new().write_atomic(&path).unwrap();

        const N: usize = 8;
        std::thread::scope(|s| {
            for i in 0..N {
                let path = path.clone();
                s.spawn(move || {
                    crate::atomic::with_exclusive_lock(&path, || {
                        let mut lock = Lockfile::load_or_default(&path).expect("load");
                        lock.upsert(
                            format!("repo-{i}"),
                            RepoLockEntry {
                                url: format!("git@example.com:acme/repo-{i}.git"),
                                r#ref: "main".to_string(),
                                sha: format!("sha-{i:03}"),
                                synced_at: fixed_time(),
                            },
                        );
                        crate::atomic::atomic_write_string(&path, &lock.to_string())
                    })
                    .expect("under lock");
                });
            }
        });

        let raw = std::fs::read_to_string(&path).expect("read final");
        let final_lock = Lockfile::parse(&raw).expect("parse final");
        assert_eq!(
            final_lock.repos.len(),
            N,
            "lost-update under concurrent sync; got {} entries, expected {N}; raw:\n{raw}",
            final_lock.repos.len()
        );
        for i in 0..N {
            let name = format!("repo-{i}");
            assert!(
                final_lock.repos.contains_key(&name),
                "missing {name} after concurrent upsert"
            );
        }
    }
}
