//! `coral test --emit k6` — translate the discovered + filtered
//! `TestCase` set into a single k6 JavaScript load-test script.
//!
//! v0.22.2 covers the smoke→load handoff: the same TestCase pipeline
//! that `coral test` consumes is serialized to a JS file the user can
//! pipe into `k6 run`. Coral itself never executes k6 — that's the
//! handoff point.
//!
//! ## Design rationale
//!
//! - Emitter sits in `coral-test` next to `JunitOutput`: same crate,
//!   same audience (CI plumbing), same layering (no live env required
//!   beyond `EnvironmentSpec`).
//! - Pure string formatting — zero new workspace dependencies. No JS
//!   AST, no template engine. Output is `format!` + `String::push_str`.
//! - `EnvironmentSpec` (not `EnvHandle`): so emit works on a clean
//!   checkout without `coral up` having ever been run. The published
//!   port number comes from `RealService::ports[0]` (declared port,
//!   not allocated host port — k6 runs on the user's host, so they
//!   get to override per-env via `__ENV.CORAL_<NAME>_BASE`).
//! - Skip telemetry: cases we can't translate (TCP/Exec/Grpc
//!   healthchecks, exec steps in user-defined suites) are emitted
//!   as `// SKIPPED` comments AND added to `EmitOutput.skipped` so
//!   the CLI can surface a stderr summary.
//! - Determinism: cases iterate in `(service, id)` lexicographic
//!   order so two runs against the same inputs produce byte-identical
//!   output. Snapshot-test friendly.
//!
//! ## Output structure
//!
//! ```javascript
//! // Header: imports + options + per-service BASE consts
//! import http from 'k6/http';
//! import { check, sleep } from 'k6';
//! export const options = { ... };
//! const SVC_API_BASE = __ENV.CORAL_API_BASE || 'http://localhost:3000';
//! const BASE = SVC_API_BASE;
//!
//! export default function () {
//!   // === <id>: <name> (service=<svc>, tags=[...]) ===
//!   const r0 = http.get(`${SVC_API_BASE}/users`, null, { headers: {} });
//!   check(r0, { '<id>:0 status 200': (r) => r.status === 200 });
//!   sleep(1);
//! }
//!
//! // === Coral emit summary: included=N skipped=M ===
//! ```

use crate::spec::{TestCase, TestKind};
use crate::user_defined_runner::{HttpStep, YamlStep, YamlSuite};
use coral_env::{EnvironmentSpec, HealthcheckKind, ServiceKind};
use serde::{Deserialize, Serialize};

/// Public output from `emit_k6`.
#[derive(Debug, Clone)]
pub struct EmitOutput {
    /// Rendered k6 JavaScript script (UTF-8). Always ends with `\n`.
    pub script: String,
    /// Number of TestCases that contributed body blocks.
    pub included: usize,
    /// Cases that were skipped, with structured reason. Surfaced via
    /// `// SKIPPED ...` comments in the script AND returned here so
    /// the CLI can render a stderr summary.
    pub skipped: Vec<SkipNote>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SkipNote {
    pub case_id: String,
    pub reason: SkipReason,
    /// Human-readable detail line (mirrors the comment emitted in the
    /// script).
    pub detail: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SkipReason {
    /// `kind == Healthcheck` but the underlying probe is TCP/Exec/Grpc
    /// (k6 only speaks HTTP).
    HealthcheckNotHttp,
    /// `YamlStep::Exec` inside a UserDefined suite — shells out, can't
    /// translate to k6.
    UserDefinedExecStep,
    /// `kind` is one of the v0.19+ reserved kinds we can't yet emit.
    UnsupportedKind,
    /// User-defined suite that didn't deserialize as `YamlSuite`
    /// (Hurl-imported or otherwise malformed).
    InvalidUserDefinedSpec,
}

/// Translate `cases` into a single k6 JS script using `spec` for
/// per-service base URLs. Cases iterate in `(service, id)` lexicographic
/// order so two runs against the same inputs produce byte-identical
/// output (acceptance #11).
pub fn emit_k6(cases: &[TestCase], spec: &EnvironmentSpec) -> EmitOutput {
    let mut script = String::with_capacity(2048);
    let mut skipped: Vec<SkipNote> = Vec::new();

    // ---- Header --------------------------------------------------
    script.push_str("// Generated by `coral test --emit k6` — do not edit by hand.\n");
    script.push_str("// Run with: k6 run <this file>\n");
    script.push_str("import http from 'k6/http';\n");
    script.push_str("import { check, sleep } from 'k6';\n");
    script.push('\n');
    script.push_str(
        "export const options = {\n  vus: __ENV.VUS || 10,\n  duration: __ENV.DURATION || '30s',\n};\n",
    );
    script.push('\n');

    // ---- Per-service BASE consts --------------------------------
    // Walk `spec.services` in BTreeMap order (already sorted) and emit
    // one `SVC_<UPPER>_BASE` per service that declares a port. Services
    // without a port still get an entry pointing at the conventional
    // localhost:3000 — this keeps `${SVC_<NAME>_BASE}` placeholders
    // valid even when a user hand-edits the emitted file.
    let services_with_ports = collect_service_ports(spec);
    for (name, port) in &services_with_ports {
        // Service names allow dashes / dots (e.g. `my-api`, `db.primary`),
        // but JavaScript identifiers and shell env-var names do not.
        // Sanitize the same way for both `SVC_<IDENT>_BASE` (JS const) and
        // `CORAL_<IDENT>_BASE` (env-var override) so the two stay in sync.
        let ident = to_js_ident(name);
        script.push_str(&format!(
            "const SVC_{ident}_BASE = __ENV.CORAL_{ident}_BASE || 'http://localhost:{port}';\n"
        ));
    }
    // Default BASE: first service's URL or fallback. Some emitted
    // bodies reference `BASE` directly when the case has no service.
    if let Some((first_name, _)) = services_with_ports.first() {
        let ident = to_js_ident(first_name);
        script.push_str(&format!("const BASE = SVC_{ident}_BASE;\n"));
    } else {
        script.push_str("const BASE = __ENV.CORAL_BASE || 'http://localhost:3000';\n");
    }
    script.push('\n');

    // ---- Body: one block per case in deterministic order --------
    let mut sorted: Vec<&TestCase> = cases.iter().collect();
    sorted.sort_by(|a, b| {
        let svc_a = a.service.as_deref().unwrap_or("");
        let svc_b = b.service.as_deref().unwrap_or("");
        (svc_a, &a.id).cmp(&(svc_b, &b.id))
    });

    let mut included = 0usize;
    script.push_str("export default function () {\n");
    for case in &sorted {
        match emit_case(case, spec, &services_with_ports) {
            CaseOutcome::Included(block) => {
                script.push_str(&block);
                script.push_str("  sleep(1);\n");
                included += 1;
            }
            CaseOutcome::Skipped(note) => {
                script.push_str(&format!("  // SKIPPED {}: {}\n", note.case_id, note.detail));
                skipped.push(note);
            }
        }
    }
    script.push_str("}\n");
    script.push('\n');

    // ---- Footer -------------------------------------------------
    script.push_str(&format!(
        "// === Coral emit summary: included={} skipped={} ===\n",
        included,
        skipped.len()
    ));

    EmitOutput {
        script,
        included,
        skipped,
    }
}

/// Walk `spec.services` and return `(name, port)` pairs in BTreeMap
/// order. Mocks and services without ports are skipped — only services
/// with a published port get a `SVC_<NAME>_BASE` const.
fn collect_service_ports(spec: &EnvironmentSpec) -> Vec<(String, u16)> {
    let mut out = Vec::new();
    for (name, kind) in &spec.services {
        if let ServiceKind::Real(real) = kind {
            if let Some(&port) = real.ports.first() {
                out.push((name.clone(), port));
            }
        }
    }
    out
}

enum CaseOutcome {
    Included(String),
    Skipped(SkipNote),
}

/// Translate a single TestCase into either a `String` body block (one
/// or more `http.<method>` + `check` calls) or a `SkipNote`.
fn emit_case(
    case: &TestCase,
    spec: &EnvironmentSpec,
    services_with_ports: &[(String, u16)],
) -> CaseOutcome {
    match case.kind {
        TestKind::UserDefined => emit_user_defined(case, services_with_ports),
        TestKind::Healthcheck => emit_healthcheck(case, spec, services_with_ports),
        other => CaseOutcome::Skipped(SkipNote {
            case_id: case.id.clone(),
            reason: SkipReason::UnsupportedKind,
            detail: format!(
                "kind {other:?} is not k6-compatible (v0.22.2 covers UserDefined HTTP + HTTP Healthcheck)"
            ),
        }),
    }
}

fn emit_user_defined(case: &TestCase, services_with_ports: &[(String, u16)]) -> CaseOutcome {
    let suite: YamlSuite = match serde_json::from_value(case.spec.0.clone()) {
        Ok(s) => s,
        Err(e) => {
            return CaseOutcome::Skipped(SkipNote {
                case_id: case.id.clone(),
                reason: SkipReason::InvalidUserDefinedSpec,
                detail: format!("could not deserialize user-defined spec: {e}"),
            });
        }
    };

    let mut block = String::with_capacity(256);
    block.push_str(&fence(case));
    let svc_const = service_base_const(case.service.as_deref(), services_with_ports);
    let mut emitted_any = false;
    for (idx, step) in suite.steps.iter().enumerate() {
        match step {
            YamlStep::Http(http) => {
                let step_block = emit_http_step(case, idx, http, &svc_const);
                block.push_str(&step_block);
                emitted_any = true;
            }
            YamlStep::Exec(_) => {
                block.push_str(&format!(
                    "  // SKIPPED {}:{idx} — exec step not k6-compatible\n",
                    case.id
                ));
                // Track in EmitOutput.skipped at case level only when
                // ALL steps are skipped; per-step exec skips are inline
                // comments. Keep skip-list crisp for CLI summary.
            }
        }
    }
    if !emitted_any {
        // All steps were exec — surface as a case-level skip so the
        // CLI summary names the case.
        return CaseOutcome::Skipped(SkipNote {
            case_id: case.id.clone(),
            reason: SkipReason::UserDefinedExecStep,
            detail: format!(
                "user-defined suite '{}' has no http steps (only exec)",
                case.name
            ),
        });
    }
    CaseOutcome::Included(block)
}

fn emit_http_step(case: &TestCase, idx: usize, step: &HttpStep, svc_const: &ServiceBase) -> String {
    let mut out = String::with_capacity(160);
    let (method, path) = match split_http_line(&step.http) {
        Some(t) => t,
        None => {
            out.push_str(&format!(
                "  // SKIPPED {}:{idx} — invalid http line: {}\n",
                case.id, step.http
            ));
            return out;
        }
    };
    let url = match svc_const {
        ServiceBase::Const(name) => format!("`${{{name}}}{path}`"),
        ServiceBase::FallbackBase(svc) => {
            // `service` was set on the case but didn't match any
            // declared service — drop a TODO so the user can wire it
            // manually. Use `BASE` as a placeholder so the script still
            // parses.
            out.push_str(&format!(
                "  // TODO {}:{idx} — service '{svc}' not declared in environment; using BASE\n",
                case.id
            ));
            format!("`${{BASE}}{path}`")
        }
        ServiceBase::Default => format!("`${{BASE}}{path}`"),
    };

    let body_arg = if let Some(body) = &step.body {
        format!("JSON.stringify({})", body)
    } else {
        "null".to_string()
    };
    let headers_arg = render_headers(&step.headers, step.body.is_some());

    let var = format!("r{idx}");
    let method_lc = method.to_lowercase();
    out.push_str(&format!(
        "  const {var} = http.{method_lc}({url}, {body_arg}, {headers_arg});\n"
    ));
    out.push_str(&render_checks(case, idx, &step.expect, &var));
    out
}

fn render_headers(headers: &std::collections::BTreeMap<String, String>, has_body: bool) -> String {
    if headers.is_empty() && !has_body {
        return "{ headers: {} }".to_string();
    }
    let mut s = String::from("{ headers: { ");
    let mut first = true;
    if has_body && !headers.contains_key("Content-Type") {
        s.push_str("'Content-Type': 'application/json'");
        first = false;
    }
    for (k, v) in headers {
        if !first {
            s.push_str(", ");
        }
        s.push_str(&format!("{}: {}", js_string(k), js_string(v)));
        first = false;
    }
    s.push_str(" } }");
    s
}

fn render_checks(
    case: &TestCase,
    idx: usize,
    expect: &crate::user_defined_runner::HttpExpect,
    var: &str,
) -> String {
    let mut clauses: Vec<String> = Vec::new();
    if let Some(status) = expect.status {
        clauses.push(format!(
            "    {label}: (r) => r.status === {status}",
            label = js_string(&format!("{}:{} status {}", case.id, idx, status))
        ));
    }
    if let Some(needle) = &expect.body_contains {
        clauses.push(format!(
            "    {label}: (r) => r.body.includes({needle})",
            label = js_string(&format!("{}:{} body contains {}", case.id, idx, needle)),
            needle = js_string(needle)
        ));
    }
    if expect.snapshot.is_some() {
        // Snapshot expects don't translate — leave a comment so the
        // user knows the case had one.
        let mut s = String::new();
        if !clauses.is_empty() {
            s.push_str(&format!("  check({var}, {{\n"));
            s.push_str(&clauses.join(",\n"));
            s.push_str("\n  });\n");
        }
        s.push_str(&format!(
            "  /* {}:{idx} snapshot expect skipped — k6 doesn't do snapshots */\n",
            case.id
        ));
        return s;
    }
    if clauses.is_empty() {
        // No assertions at all — skip the `check()` block entirely.
        return String::new();
    }
    let mut s = String::new();
    s.push_str(&format!("  check({var}, {{\n"));
    s.push_str(&clauses.join(",\n"));
    s.push_str("\n  });\n");
    s
}

/// One of: `SVC_<NAME>_BASE` const, `BASE` fallback for unknown service,
/// or `BASE` default for service-less case.
enum ServiceBase {
    Const(String),
    FallbackBase(String),
    Default,
}

fn service_base_const(service: Option<&str>, services_with_ports: &[(String, u16)]) -> ServiceBase {
    match service {
        Some(name) => {
            if services_with_ports.iter().any(|(n, _)| n == name) {
                // `to_js_ident` matches the header emission so the body
                // reference resolves to the declared const (dashes /
                // dots in service names map to underscores).
                ServiceBase::Const(format!("SVC_{}_BASE", to_js_ident(name)))
            } else {
                ServiceBase::FallbackBase(name.to_string())
            }
        }
        None => ServiceBase::Default,
    }
}

/// Render a Healthcheck case. HTTP probes translate to `http.get` +
/// 2xx check; TCP/Exec/Grpc probes are skipped with a structured
/// `SkipNote` (acceptance #6).
fn emit_healthcheck(
    case: &TestCase,
    spec: &EnvironmentSpec,
    services_with_ports: &[(String, u16)],
) -> CaseOutcome {
    let service = match case.service.as_deref() {
        Some(s) => s,
        None => {
            return CaseOutcome::Skipped(SkipNote {
                case_id: case.id.clone(),
                reason: SkipReason::HealthcheckNotHttp,
                detail: "healthcheck case has no service".into(),
            });
        }
    };
    let probe_kind = healthcheck_probe_label(spec, service);
    if probe_kind != "http" {
        return CaseOutcome::Skipped(SkipNote {
            case_id: case.id.clone(),
            reason: SkipReason::HealthcheckNotHttp,
            detail: format!(
                "healthcheck kind '{probe_kind}' is not k6-compatible (only http probes translate)"
            ),
        });
    }
    // HTTP probe: pull the path off the spec.
    let path = healthcheck_http_path(spec, service).unwrap_or_else(|| "/health".to_string());
    let svc_const = service_base_const(Some(service), services_with_ports);
    let url = match &svc_const {
        ServiceBase::Const(name) => format!("`${{{name}}}{path}`"),
        ServiceBase::FallbackBase(_) | ServiceBase::Default => format!("`${{BASE}}{path}`"),
    };
    let mut block = String::new();
    block.push_str(&fence(case));
    block.push_str(&format!(
        "  const r0 = http.get({url}, null, {{ headers: {{}} }});\n"
    ));
    block.push_str(&format!(
        "  check(r0, {{\n    {label}: (r) => r.status >= 200 && r.status < 300\n  }});\n",
        label = js_string(&format!("{}:0 status 2xx", case.id))
    ));
    CaseOutcome::Included(block)
}

/// "// === id: name (service=svc, tags=[...]) ===\n" header for one
/// case body block. Matches the structure declared in spec §3b.
fn fence(case: &TestCase) -> String {
    let svc = case.service.as_deref().unwrap_or("none");
    let tags = if case.tags.is_empty() {
        String::new()
    } else {
        case.tags.join(",")
    };
    format!(
        "  // === {id}: {name} (service={svc}, tags=[{tags}]) ===\n",
        id = case.id,
        name = case.name
    )
}

/// Parse `"GET /path"` into `("GET", "/path")` — same shape as
/// `user_defined_runner::parse_http_line` but returns owned `String`s
/// so the emitter can format them into URLs without lifetime
/// gymnastics.
fn split_http_line(line: &str) -> Option<(&'static str, String)> {
    let mut parts = line.splitn(2, ' ');
    let method = match parts.next()?.trim() {
        "GET" => "GET",
        "POST" => "POST",
        "PUT" => "PUT",
        "DELETE" => "DELETE",
        "PATCH" => "PATCH",
        "HEAD" => "HEAD",
        "OPTIONS" => "OPTIONS",
        _ => return None,
    };
    let path = parts.next()?.trim().to_string();
    if path.is_empty() {
        return None;
    }
    Some((method, path))
}

/// Sanitize a service name (e.g. `my-api`, `db.primary`) into a token
/// that is safe to splice into BOTH a JS `const` identifier and a
/// shell env-var name. Coral allows dashes and dots in service names
/// (the manifest schema is permissive); JavaScript identifiers and
/// POSIX env-vars do not — both must match `[A-Z_][A-Z0-9_]*`.
///
/// Transform: uppercase, then map `-` and `.` to `_`. The result is
/// then validated against `^[A-Z_][A-Z0-9_]*$`; if a name contains an
/// unmappable character (whitespace, `@`, …) we fall back to a
/// deterministic alphanumeric digest so the script still parses.
/// Regression: `my-api` (HIGH bug, v0.22.2) → `MY_API`, both
/// `SVC_MY_API_BASE` and `__ENV.CORAL_MY_API_BASE` emitted.
fn to_js_ident(name: &str) -> String {
    let upper = name.to_uppercase();
    let mapped: String = upper
        .chars()
        .map(|c| if c == '-' || c == '.' { '_' } else { c })
        .collect();
    if is_valid_js_ident(&mapped) {
        return mapped;
    }
    // Fallback: replace any non-`[A-Z0-9_]` character with `_`, then
    // ensure the leading char isn't a digit. Deterministic, lossy but
    // syntactically safe — matches the contract above (script parses).
    let mut out: String = mapped
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        out.insert(0, '_');
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// True iff `s` is a non-empty ASCII string matching `^[A-Z_][A-Z0-9_]*$`
/// — the strict subset of JS identifiers (and POSIX env-var names) the
/// k6 emitter relies on.
fn is_valid_js_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c.is_ascii_uppercase() => {}
        _ => return false,
    }
    chars.all(|c| c == '_' || c.is_ascii_uppercase() || c.is_ascii_digit())
}

/// Render `s` as a single-quoted JS string, escaping single quotes and
/// backslashes. Adequate for the labels and header values we emit;
/// k6 parses with V8 so this is the same escaping rules as
/// `JSON.stringify` modulo the quote style.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

// -----------------------------------------------------------------
// Healthcheck probe-kind plumbing.
//
// `emit_k6` needs access to per-service probe shapes (HTTP path vs
// TCP port vs exec vs grpc) to decide whether each Healthcheck case
// translates to an `http.get` or a `// SKIPPED` comment. The simplest
// way to thread that through without bloating the public API is to
// re-walk `spec.services` here and build a side-table. The performance
// cost is O(services) — trivial for any realistic project.
// -----------------------------------------------------------------

/// Return Some(path) if `service`'s healthcheck is HTTP, else None.
fn healthcheck_http_path(spec: &EnvironmentSpec, service: &str) -> Option<String> {
    match spec.services.get(service)? {
        ServiceKind::Real(real) => match real.healthcheck.as_ref()?.kind {
            HealthcheckKind::Http { ref path, .. } => Some(path.clone()),
            _ => None,
        },
        _ => None,
    }
}

fn healthcheck_probe_label(spec: &EnvironmentSpec, service: &str) -> &'static str {
    match spec.services.get(service) {
        Some(ServiceKind::Real(real)) => match real.healthcheck.as_ref() {
            Some(hc) => match hc.kind {
                HealthcheckKind::Http { .. } => "http",
                HealthcheckKind::Tcp { .. } => "tcp",
                HealthcheckKind::Exec { .. } => "exec",
                HealthcheckKind::Grpc { .. } => "grpc",
            },
            None => "none",
        },
        _ => "none",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{TestCase, TestKind, TestSource, TestSpec};
    use coral_env::spec::{EnvMode, Healthcheck, HealthcheckTiming, RealService};
    use std::collections::BTreeMap;

    fn empty_spec() -> EnvironmentSpec {
        EnvironmentSpec {
            name: "dev".into(),
            backend: "compose".into(),
            mode: EnvMode::Managed,
            compose_command: "auto".into(),
            production: false,
            env_file: None,
            services: BTreeMap::new(),
            chaos: None,
            chaos_scenarios: Vec::new(),
            monitors: Vec::new(),
            recorded: None,
        }
    }

    #[test]
    fn js_string_escapes_quotes_and_backslashes() {
        assert_eq!(js_string("hello"), "'hello'");
        assert_eq!(js_string("it's"), "'it\\'s'");
        assert_eq!(js_string("a\\b"), "'a\\\\b'");
    }

    #[test]
    fn to_js_ident_uppercases_and_maps_dash_and_dot() {
        // Plain alphanumeric: just uppercase.
        assert_eq!(to_js_ident("api"), "API");
        // HIGH regression (v0.22.2): dash → underscore.
        assert_eq!(to_js_ident("my-api"), "MY_API");
        // Dotted names (e.g. `db.primary`): same treatment.
        assert_eq!(to_js_ident("db.primary"), "DB_PRIMARY");
        // Mixed case input lowercases first via to_uppercase.
        assert_eq!(to_js_ident("MyApi"), "MYAPI");
        // Multiple dashes survive.
        assert_eq!(to_js_ident("user-svc-v2"), "USER_SVC_V2");
        // Underscore is preserved.
        assert_eq!(to_js_ident("user_svc"), "USER_SVC");
    }

    #[test]
    fn to_js_ident_output_always_matches_strict_ident_grammar() {
        // The contract: every output passes `is_valid_js_ident` (so the
        // emitted JS const + shell env-var name are both syntactically
        // safe). Cover the awkward cases.
        for name in [
            "api",
            "my-api",
            "db.primary",
            "1starts_with_digit",
            "with space",
            "weird@name",
            "kebab-and-dot.x",
        ] {
            let id = to_js_ident(name);
            assert!(
                is_valid_js_ident(&id),
                "to_js_ident({name:?}) = {id:?} is not a valid JS/env-var ident"
            );
        }
    }

    #[test]
    fn is_valid_js_ident_rejects_dashes_and_leading_digits() {
        assert!(is_valid_js_ident("API"));
        assert!(is_valid_js_ident("MY_API"));
        assert!(is_valid_js_ident("_LEADING_UNDERSCORE"));
        assert!(is_valid_js_ident("X1"));
        assert!(!is_valid_js_ident(""));
        assert!(!is_valid_js_ident("MY-API"));
        assert!(!is_valid_js_ident("1API"));
        assert!(!is_valid_js_ident("api")); // strict: uppercase only
    }

    #[test]
    fn dash_in_service_name_emits_valid_js_ident() {
        // Pre-fix: `my-api` produced `SVC_MY-API_BASE` and crashed
        // `node --check`. Post-fix: `MY_API` for both the const and the
        // env-var override. Pin both sites against drift.
        let mut services = BTreeMap::new();
        services.insert(
            "my-api".to_string(),
            ServiceKind::Real(Box::new(RealService {
                repo: None,
                image: Some("nginx:latest".into()),
                build: None,
                ports: vec![3000],
                env: BTreeMap::new(),
                depends_on: vec![],
                healthcheck: None,
                watch: None,
            })),
        );
        let spec = EnvironmentSpec {
            name: "dev".into(),
            backend: "compose".into(),
            mode: EnvMode::Managed,
            compose_command: "auto".into(),
            production: false,
            env_file: None,
            services,
            chaos: None,
            chaos_scenarios: Vec::new(),
            monitors: Vec::new(),
            recorded: None,
        };
        let out = emit_k6(&[], &spec);
        assert!(
            out.script.contains(
                "const SVC_MY_API_BASE = __ENV.CORAL_MY_API_BASE || 'http://localhost:3000';"
            ),
            "dash service name must produce JS-safe const + env-var; got: {}",
            out.script
        );
        assert!(
            out.script.contains("const BASE = SVC_MY_API_BASE;"),
            "BASE alias must reference the sanitized const; got: {}",
            out.script
        );
        // Double-check we never emit the broken pre-fix form.
        assert!(
            !out.script.contains("SVC_MY-API_BASE"),
            "must not emit pre-fix unsanitized form: {}",
            out.script
        );
    }

    #[test]
    fn split_http_line_recognizes_methods() {
        assert_eq!(split_http_line("GET /x"), Some(("GET", "/x".into())));
        assert_eq!(split_http_line("POST /x"), Some(("POST", "/x".into())));
        assert_eq!(split_http_line("FOO /x"), None);
    }

    #[test]
    fn empty_cases_produces_valid_skeleton() {
        let out = emit_k6(&[], &empty_spec());
        assert_eq!(out.included, 0);
        assert!(out.script.contains("import http from 'k6/http';"));
        assert!(out.script.contains("import { check, sleep } from 'k6';"));
        assert!(out.script.contains("export const options"));
        assert!(out.script.contains("export default function () {"));
        assert!(
            out.script
                .contains("// === Coral emit summary: included=0 skipped=0 ===")
        );
    }

    #[test]
    #[allow(non_snake_case)]
    fn empty_spec_uses_BASE_default() {
        let out = emit_k6(&[], &empty_spec());
        assert!(
            out.script
                .contains("const BASE = __ENV.CORAL_BASE || 'http://localhost:3000';"),
            "got: {}",
            out.script
        );
    }

    fn spec_with_api_port(port: u16) -> EnvironmentSpec {
        let mut services = BTreeMap::new();
        services.insert(
            "api".to_string(),
            ServiceKind::Real(Box::new(RealService {
                repo: None,
                image: Some("nginx:latest".into()),
                build: None,
                ports: vec![port],
                env: BTreeMap::new(),
                depends_on: vec![],
                healthcheck: None,
                watch: None,
            })),
        );
        EnvironmentSpec {
            name: "dev".into(),
            backend: "compose".into(),
            mode: EnvMode::Managed,
            compose_command: "auto".into(),
            production: false,
            env_file: None,
            services,
            chaos: None,
            chaos_scenarios: Vec::new(),
            monitors: Vec::new(),
            recorded: None,
        }
    }

    #[test]
    fn service_with_port_emits_typed_base_const() {
        let out = emit_k6(&[], &spec_with_api_port(8080));
        assert!(
            out.script
                .contains("const SVC_API_BASE = __ENV.CORAL_API_BASE || 'http://localhost:8080';"),
            "got: {}",
            out.script
        );
        // First service becomes BASE.
        assert!(
            out.script.contains("const BASE = SVC_API_BASE;"),
            "got: {}",
            out.script
        );
    }

    fn user_defined_case(id: &str, suite: YamlSuite) -> TestCase {
        TestCase {
            id: id.to_string(),
            name: id.to_string(),
            kind: TestKind::UserDefined,
            service: suite.service.clone(),
            tags: suite.tags.clone(),
            source: TestSource::Inline,
            spec: TestSpec(serde_json::to_value(&suite).unwrap()),
        }
    }

    #[test]
    fn user_defined_two_step_emits_two_http_calls() {
        let yaml = r#"
name: api smoke
service: api
steps:
  - http: GET /users
    expect: { status: 200 }
  - http: POST /users
    body: { name: "alice" }
    expect: { status: 201, body_contains: "alice" }
"#;
        let suite: YamlSuite = serde_yaml_ng::from_str(yaml).unwrap();
        let case = user_defined_case("user-defined:api smoke", suite);
        let out = emit_k6(&[case], &spec_with_api_port(3000));
        assert_eq!(out.included, 1);
        assert!(out.script.contains("http.get(`${SVC_API_BASE}/users`"));
        assert!(out.script.contains("http.post(`${SVC_API_BASE}/users`"));
        assert!(out.script.contains("(r) => r.status === 200"));
        assert!(out.script.contains("(r) => r.status === 201"));
        assert!(out.script.contains("(r) => r.body.includes('alice')"));
    }

    #[test]
    fn exec_step_inside_user_defined_is_skipped_with_inline_comment() {
        let yaml = r#"
name: mixed
service: api
steps:
  - http: GET /health
    expect: { status: 200 }
  - exec: ["echo", "ok"]
"#;
        let suite: YamlSuite = serde_yaml_ng::from_str(yaml).unwrap();
        let case = user_defined_case("user-defined:mixed", suite);
        let out = emit_k6(&[case], &spec_with_api_port(3000));
        assert_eq!(out.included, 1);
        assert!(
            out.script
                .contains("// SKIPPED user-defined:mixed:1 — exec step not k6-compatible"),
            "got: {}",
            out.script
        );
    }

    fn healthcheck_case_for(service: &str) -> TestCase {
        TestCase {
            id: format!("healthcheck:{service}"),
            name: format!("{service} healthcheck"),
            kind: TestKind::Healthcheck,
            service: Some(service.to_string()),
            tags: vec!["healthcheck".into(), "smoke".into()],
            source: TestSource::Inline,
            spec: TestSpec::empty(),
        }
    }

    fn spec_with_http_healthcheck() -> EnvironmentSpec {
        let mut s = spec_with_api_port(3000);
        if let ServiceKind::Real(real) = s.services.get_mut("api").unwrap() {
            real.healthcheck = Some(Healthcheck {
                kind: HealthcheckKind::Http {
                    path: "/healthz".into(),
                    expect_status: 200,
                    headers: BTreeMap::new(),
                },
                timing: HealthcheckTiming::default(),
            });
        }
        s
    }

    #[test]
    fn http_healthcheck_emits_get_and_2xx_check() {
        let case = healthcheck_case_for("api");
        let out = emit_k6(&[case], &spec_with_http_healthcheck());
        assert_eq!(out.included, 1);
        assert!(
            out.script.contains("http.get(`${SVC_API_BASE}/healthz`"),
            "got: {}",
            out.script
        );
        assert!(
            out.script
                .contains("(r) => r.status >= 200 && r.status < 300"),
            "got: {}",
            out.script
        );
    }

    #[test]
    fn healthcheck_probe_label_distinguishes_kinds() {
        let mut s = spec_with_api_port(3000);
        if let ServiceKind::Real(real) = s.services.get_mut("api").unwrap() {
            real.healthcheck = Some(Healthcheck {
                kind: HealthcheckKind::Tcp { port: 3000 },
                timing: HealthcheckTiming::default(),
            });
        }
        assert_eq!(healthcheck_probe_label(&s, "api"), "tcp");
    }

    #[test]
    fn healthcheck_http_path_returns_path() {
        let s = spec_with_http_healthcheck();
        assert_eq!(
            healthcheck_http_path(&s, "api").as_deref(),
            Some("/healthz")
        );
    }
}
