//! `coral ci generate` — emit a CI template for the project.

use anyhow::Result;
use clap::{Args, Subcommand};
use std::process::ExitCode;

#[derive(Args, Debug)]
pub struct CiArgs {
    #[command(subcommand)]
    pub command: CiCmd,
}

#[derive(Subcommand, Debug)]
pub enum CiCmd {
    /// Generate a GitHub Actions workflow that runs the deployment gate.
    Generate(GenerateArgs),
}

#[derive(Args, Debug)]
pub struct GenerateArgs {
    /// Output path. Defaults to `.github/workflows/coral-guarantee.yml`.
    #[arg(long)]
    pub output: Option<String>,

    /// Print to stdout instead of writing to file.
    #[arg(long)]
    pub stdout: bool,
}

pub fn run(args: CiArgs) -> Result<ExitCode> {
    match args.command {
        CiCmd::Generate(g) => generate(g),
    }
}

fn generate(args: GenerateArgs) -> Result<ExitCode> {
    let yaml = ci_workflow_template();

    if args.stdout {
        println!("{yaml}");
    } else {
        let path = args
            .output
            .unwrap_or_else(|| ".github/workflows/coral-guarantee.yml".to_string());
        let parent = std::path::Path::new(&path).parent();
        if let Some(p) = parent {
            std::fs::create_dir_all(p)?;
        }
        std::fs::write(&path, &yaml)?;
        eprintln!("wrote {path}");
    }

    Ok(ExitCode::SUCCESS)
}

fn ci_workflow_template() -> String {
    r#"# Generated by `coral ci generate` — safe to customize.
name: Coral Deployment Gate

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  coral-guarantee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Coral
        run: cargo install --path . --locked

      - name: Run deployment gate
        run: coral guarantee --can-i-deploy --strict --format github-actions
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_contains_guarantee_command() {
        let yaml = ci_workflow_template();
        assert!(yaml.contains("coral guarantee --can-i-deploy --strict --format github-actions"));
        assert!(yaml.contains("actions/checkout@v4"));
        assert!(yaml.contains("fetch-depth: 0"));
    }

    #[test]
    fn generate_stdout_prints_yaml() {
        // Just verify it doesn't panic
        let yaml = ci_workflow_template();
        assert!(yaml.starts_with('#'));
        assert!(yaml.contains("name:"));
    }
}
