//! Export the wiki to various target formats: Markdown bundle, raw JSON,
//! Notion API page-create bodies, JSONL for fine-tuning datasets.

use anyhow::{Context, Result};
use clap::Args;
use coral_core::page::Page;
use coral_core::walk;
use serde_json::json;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

#[derive(Args, Debug)]
pub struct ExportArgs {
    /// Output format. Choose: markdown-bundle | json | notion-json | jsonl.
    #[arg(long, default_value = "markdown-bundle")]
    pub format: String,
    /// Optional output file. If absent, prints to stdout.
    #[arg(long)]
    pub out: Option<PathBuf>,
    /// Filter by page type (repeatable). Example: --type module --type concept.
    /// If empty, exports all types.
    #[arg(long = "type", value_name = "TYPE")]
    pub types: Vec<String>,
}

pub fn run(args: ExportArgs, wiki_root: Option<&Path>) -> Result<ExitCode> {
    let root = wiki_root
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from(".wiki"));
    if !root.exists() {
        anyhow::bail!(
            "wiki root not found: {}. Run `coral init` first.",
            root.display()
        );
    }

    let pages = walk::read_pages(&root)
        .with_context(|| format!("reading pages from {}", root.display()))?;
    let pages: Vec<Page> = if args.types.is_empty() {
        pages
    } else {
        let allow: std::collections::HashSet<&str> =
            args.types.iter().map(String::as_str).collect();
        pages
            .into_iter()
            .filter(|p| allow.contains(page_type_name(&p.frontmatter)))
            .collect()
    };

    let output = match args.format.as_str() {
        "markdown-bundle" => render_markdown_bundle(&pages),
        "json" => render_json(&pages)?,
        "notion-json" => render_notion_json(&pages)?,
        "jsonl" => render_jsonl(&pages)?,
        other => anyhow::bail!(
            "unknown format: {other}. Choose: markdown-bundle | json | notion-json | jsonl"
        ),
    };

    if let Some(path) = &args.out {
        std::fs::write(path, &output).with_context(|| format!("writing {}", path.display()))?;
        eprintln!("Wrote {} bytes to {}.", output.len(), path.display());
    } else {
        print!("{output}");
    }
    Ok(ExitCode::SUCCESS)
}

fn page_type_name(fm: &coral_core::frontmatter::Frontmatter) -> &'static str {
    use coral_core::frontmatter::PageType::*;
    match fm.page_type {
        Module => "module",
        Concept => "concept",
        Entity => "entity",
        Flow => "flow",
        Decision => "decision",
        Synthesis => "synthesis",
        Operation => "operation",
        Source => "source",
        Gap => "gap",
        Index => "index",
        Log => "log",
        Schema => "schema",
        Readme => "readme",
        Reference => "reference",
    }
}

fn status_name(fm: &coral_core::frontmatter::Frontmatter) -> &'static str {
    use coral_core::frontmatter::Status::*;
    match fm.status {
        Draft => "draft",
        Reviewed => "reviewed",
        Verified => "verified",
        Stale => "stale",
        Archived => "archived",
        Reference => "reference",
    }
}

fn render_markdown_bundle(pages: &[Page]) -> String {
    let mut out = String::from(
        "# Wiki bundle\n\nGenerated by `coral export --format markdown-bundle`.\n\n---\n\n",
    );
    for p in pages {
        out.push_str(&format!(
            "## {} ({})\n\n_status: {}, confidence: {:.2}_\n\n{}\n\n---\n\n",
            p.frontmatter.slug,
            page_type_name(&p.frontmatter),
            status_name(&p.frontmatter),
            p.frontmatter.confidence.as_f64(),
            p.body.trim()
        ));
    }
    out
}

fn render_json(pages: &[Page]) -> Result<String> {
    let arr: Vec<_> = pages
        .iter()
        .map(|p| {
            json!({
                "slug": p.frontmatter.slug,
                "type": page_type_name(&p.frontmatter),
                "status": status_name(&p.frontmatter),
                "confidence": p.frontmatter.confidence.as_f64(),
                "sources": p.frontmatter.sources,
                "backlinks": p.frontmatter.backlinks,
                "body": p.body,
            })
        })
        .collect();
    Ok(serde_json::to_string_pretty(&arr)?)
}

fn render_notion_json(pages: &[Page]) -> Result<String> {
    // Each entry follows the Notion `POST /v1/pages` request body shape.
    // The consumer fills in `parent.database_id` from their config.
    let arr: Vec<_> = pages
        .iter()
        .map(|p| {
            json!({
                "parent": { "database_id": "<set-from-config>" },
                "properties": {
                    "Name": {
                        "title": [{ "text": { "content": p.frontmatter.slug } }]
                    },
                    "Type": {
                        "select": { "name": page_type_name(&p.frontmatter) }
                    },
                    "Status": {
                        "select": { "name": status_name(&p.frontmatter) }
                    },
                    "Confidence": {
                        "number": p.frontmatter.confidence.as_f64()
                    }
                },
                "children": [{
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{
                            "type": "text",
                            "text": { "content": p.body.chars().take(2000).collect::<String>() }
                        }]
                    }
                }]
            })
        })
        .collect();
    Ok(serde_json::to_string_pretty(&arr)?)
}

fn render_jsonl(pages: &[Page]) -> Result<String> {
    // One JSON object per line. v0.2 ships raw page data with a stub prompt.
    // v0.3 will use the runner to generate Q/A pairs for fine-tuning.
    let mut out = String::new();
    for p in pages {
        let line = json!({
            "slug": p.frontmatter.slug,
            "body": p.body,
            "prompt": format!("Tell me about [[{}]] in this wiki.", p.frontmatter.slug),
        });
        out.push_str(&serde_json::to_string(&line)?);
        out.push('\n');
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use coral_core::frontmatter::{Confidence, Frontmatter, PageType, Status};
    use std::path::PathBuf;

    fn page(slug: &str, page_type: PageType, body: &str) -> Page {
        Page {
            path: PathBuf::from(format!(".wiki/modules/{slug}.md")),
            frontmatter: Frontmatter {
                slug: slug.to_string(),
                page_type,
                last_updated_commit: "abc".to_string(),
                confidence: Confidence::try_new(0.8).unwrap(),
                sources: vec!["src/x.rs".into()],
                backlinks: vec![],
                status: Status::Reviewed,
                generated_at: None,
                extra: Default::default(),
            },
            body: body.to_string(),
        }
    }

    #[test]
    fn markdown_bundle_includes_all_pages() {
        let pages = vec![
            page("order", PageType::Module, "Order body."),
            page("idempotency", PageType::Concept, "Idempotency body."),
        ];
        let out = render_markdown_bundle(&pages);
        assert!(out.contains("## order (module)"));
        assert!(out.contains("## idempotency (concept)"));
        assert!(out.contains("Order body."));
        assert!(out.contains("Idempotency body."));
    }

    #[test]
    fn json_format_is_valid() {
        let pages = vec![page("x", PageType::Module, "body")];
        let out = render_json(&pages).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(parsed[0]["slug"], "x");
        assert_eq!(parsed[0]["type"], "module");
    }

    #[test]
    fn notion_json_has_expected_shape() {
        let pages = vec![page("x", PageType::Module, "body")];
        let out = render_notion_json(&pages).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert!(parsed[0]["parent"]["database_id"].is_string());
        assert_eq!(
            parsed[0]["properties"]["Name"]["title"][0]["text"]["content"],
            "x"
        );
        assert_eq!(parsed[0]["properties"]["Type"]["select"]["name"], "module");
    }

    #[test]
    fn jsonl_emits_one_line_per_page() {
        let pages = vec![
            page("a", PageType::Module, "body a"),
            page("b", PageType::Concept, "body b"),
        ];
        let out = render_jsonl(&pages).unwrap();
        let lines: Vec<_> = out.lines().collect();
        assert_eq!(lines.len(), 2);
        for line in lines {
            let _: serde_json::Value = serde_json::from_str(line).unwrap();
        }
    }

    #[test]
    fn jsonl_includes_stub_prompt() {
        let pages = vec![page("x", PageType::Module, "body")];
        let out = render_jsonl(&pages).unwrap();
        assert!(out.contains("Tell me about [[x]]"));
    }
}
