use anyhow::{Context, Result};
use clap::Args;
use coral_core::frontmatter::{Confidence, Frontmatter, PageType, Status};
use coral_core::page::Page;
use coral_core::walk;
use coral_runner::{Prompt, Runner};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

#[derive(Args, Debug, Default)]
pub struct OnboardArgs {
    /// Profile of the reader (e.g., "backend dev", "data engineer", "PM").
    #[arg(long, default_value = "engineer")]
    pub profile: String,
    #[arg(long)]
    pub model: Option<String>,
    /// LLM provider: claude (default) | gemini | local. Or set CORAL_PROVIDER env.
    #[arg(long)]
    pub provider: Option<String>,
    /// Apply: persist the reading path as a wiki page at
    /// `<wiki_root>/operations/onboarding-<profile>.md` (overwrites if it
    /// already exists). The slug becomes `onboarding-<profile>` (spaces
    /// dashed, lowercased). Without `--apply`, the path is printed only.
    #[arg(long)]
    pub apply: bool,
}

pub fn run(args: OnboardArgs, wiki_root: Option<&Path>) -> Result<ExitCode> {
    let provider = super::runner_helper::resolve_provider(args.provider.as_deref())
        .map_err(|e| anyhow::anyhow!(e))?;
    let runner = super::runner_helper::make_runner(provider);
    run_with_runner(args, wiki_root, runner.as_ref())
}

pub fn run_with_runner(
    args: OnboardArgs,
    wiki_root: Option<&Path>,
    runner: &dyn Runner,
) -> Result<ExitCode> {
    let root: PathBuf = wiki_root
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from(".wiki"));
    if !root.exists() {
        anyhow::bail!(
            "wiki root not found: {}. Run `coral init` first.",
            root.display()
        );
    }
    let pages = walk::read_pages(&root)
        .with_context(|| format!("reading pages from {}", root.display()))?;
    let summary = pages
        .iter()
        .map(|p| {
            format!(
                "- {} ({})",
                p.frontmatter.slug,
                serde_json::to_value(p.frontmatter.page_type)
                    .ok()
                    .and_then(|v| v.as_str().map(String::from))
                    .unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let prompt_template =
        super::prompt_loader::load_or_fallback("onboard", ONBOARD_SYSTEM_FALLBACK);
    let prompt = Prompt {
        system: Some(prompt_template.content),
        user: format!(
            "Profile: {}\n\nPages:\n{}\n\nSuggest the optimal 5–10 page reading path with 1-line rationales. Output Markdown list.",
            args.profile, summary
        ),
        model: args.model,
        cwd: None,
        timeout: None,
    };

    let out = runner
        .run(&prompt)
        .map_err(|e| anyhow::anyhow!("runner failed: {e}"))?;

    if args.apply {
        let slug = profile_to_slug(&args.profile);
        let path = persist_onboarding_page(&root, &slug, &args.profile, &out.stdout)?;
        println!(
            "# Onboarding path for `{}` written to {}\n",
            args.profile,
            path.display()
        );
        println!("{}", out.stdout);
        return Ok(ExitCode::SUCCESS);
    }

    println!("# Onboarding path for: {}\n", args.profile);
    println!("{}", out.stdout);
    println!(
        "\n_(pass `--apply` to persist as `<wiki>/operations/onboarding-{}.md`.)_",
        profile_to_slug(&args.profile)
    );
    Ok(ExitCode::SUCCESS)
}

/// Slugify a profile string for use as a filename component:
/// lowercase, spaces → dashes, drop chars that aren't `[a-z0-9-]`.
pub(crate) fn profile_to_slug(profile: &str) -> String {
    let lower = profile.to_lowercase();
    let dashed: String = lower
        .chars()
        .map(|c| match c {
            ' ' | '_' | '/' => '-',
            _ => c,
        })
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
        .collect();
    // Collapse runs of '-' and trim leading/trailing.
    let mut out = String::with_capacity(dashed.len());
    let mut prev_dash = true;
    for c in dashed.chars() {
        if c == '-' {
            if !prev_dash {
                out.push('-');
                prev_dash = true;
            }
        } else {
            out.push(c);
            prev_dash = false;
        }
    }
    out.trim_end_matches('-').to_string()
}

/// Write the onboarding page to `<root>/operations/onboarding-<slug>.md`.
/// Overwrites if it exists (the slug uniquely identifies the profile).
pub(crate) fn persist_onboarding_page(
    root: &Path,
    slug_suffix: &str,
    profile: &str,
    body_md: &str,
) -> Result<PathBuf> {
    let slug = format!("onboarding-{slug_suffix}");
    let path = root.join("operations").join(format!("{slug}.md"));
    let body = format!(
        "# Onboarding: {profile}\n\nGenerated by `coral onboard --apply`. Re-run to refresh.\n\n{}",
        body_md.trim_end()
    );
    let page = Page {
        path,
        frontmatter: Frontmatter {
            slug,
            page_type: PageType::Operation,
            last_updated_commit: head_sha(root).unwrap_or_else(|| "unknown".into()),
            confidence: Confidence::try_new(0.7).unwrap(),
            sources: vec![],
            backlinks: vec![],
            status: Status::Draft,
            generated_at: Some(chrono::Utc::now().to_rfc3339()),
            valid_from: None,
            valid_to: None,
            extra: Default::default(),
        },
        body,
    };
    page.write().context("writing onboarding page")?;
    Ok(page.path)
}

/// Resolve the repo root from the wiki root and return the HEAD SHA.
///
/// **Why this is its own helper:** the obvious one-liner
/// `gitdiff::head_sha(root.parent().unwrap_or(root))` has a quiet bug
/// — `Path::new(".wiki").parent()` returns `Some("")` (NOT `None`), so
/// `unwrap_or(root)` does not fire and `head_sha` ends up running git
/// in the empty `cwd`, producing an `ENOENT` from `execvp` on macOS.
/// The pre-v0.19.3 bug silently corrupted `last_updated_commit` to
/// `"unknown"` because the surrounding `.ok()` swallowed the error.
/// Use the centralised `repo_root_from_wiki_root` helper to get the
/// guard right.
fn head_sha(root: &Path) -> Option<String> {
    let repo_root = coral_core::path::repo_root_from_wiki_root(root);
    match coral_core::gitdiff::head_sha(&repo_root) {
        Ok(sha) => Some(sha),
        Err(e) => {
            tracing::warn!(
                error = %e,
                repo_root = %repo_root.display(),
                "head_sha failed; onboarding page will record `unknown` for last_updated_commit"
            );
            None
        }
    }
}

const ONBOARD_SYSTEM_FALLBACK: &str =
    "You are the Coral wiki onboarding guide. Suggest a reading path tailored to a profile.";

#[cfg(test)]
mod tests {
    use super::*;
    use coral_runner::MockRunner;
    use tempfile::TempDir;

    #[test]
    fn onboard_invokes_runner_with_profile() {
        let tmp = TempDir::new().unwrap();
        let wiki = tmp.path().join(".wiki");
        std::fs::create_dir_all(&wiki).unwrap();
        let runner = MockRunner::new();
        runner.push_ok("1. [[order]] — start here.");
        let exit = run_with_runner(
            OnboardArgs {
                profile: "backend dev".into(),
                model: None,
                provider: None,
                apply: false,
            },
            Some(wiki.as_path()),
            &runner,
        )
        .unwrap();
        assert_eq!(exit, ExitCode::SUCCESS);
        let calls = runner.calls();
        assert!(calls[0].user.contains("backend dev"));
    }

    #[test]
    fn onboard_apply_writes_page_at_operations_subdir() {
        let tmp = TempDir::new().unwrap();
        let wiki = tmp.path().join(".wiki");
        std::fs::create_dir_all(wiki.join("operations")).unwrap();
        let runner = MockRunner::new();
        runner.push_ok("1. [[order]] — start here.\n2. [[outbox]] — durable writes.");
        let exit = run_with_runner(
            OnboardArgs {
                profile: "Backend Dev".into(),
                model: None,
                provider: None,
                apply: true,
            },
            Some(wiki.as_path()),
            &runner,
        )
        .unwrap();
        assert_eq!(exit, ExitCode::SUCCESS);

        let written = wiki.join("operations/onboarding-backend-dev.md");
        assert!(
            written.exists(),
            "onboarding page not written at {}",
            written.display()
        );
        let on_disk = std::fs::read_to_string(&written).unwrap();
        assert!(on_disk.contains("slug: onboarding-backend-dev"));
        assert!(on_disk.contains("type: operation"));
        assert!(on_disk.contains("[[order]]"));
        assert!(on_disk.contains("[[outbox]]"));
    }

    #[test]
    fn profile_to_slug_normalizes_spaces_case_and_special_chars() {
        assert_eq!(profile_to_slug("backend dev"), "backend-dev");
        assert_eq!(profile_to_slug("Backend Dev"), "backend-dev");
        assert_eq!(profile_to_slug("data/eng"), "data-eng");
        assert_eq!(profile_to_slug("on-call SRE!"), "on-call-sre");
        assert_eq!(profile_to_slug("PM"), "pm");
        // Multiple spaces collapse to a single dash.
        assert_eq!(profile_to_slug("foo   bar"), "foo-bar");
    }
}
